
    module.exports = function (app) {
        const modelName = "offer_letter";
        const mongooseClient = app.get("mongooseClient");
        const { Schema } = mongooseClient;
        const schema = new Schema(
          {
            dealId: { type: Schema.Types.ObjectId, ref: "deals", comment: "Deal Id, dropdown, false, true, true, true, true, true, true, deals, deals, one-to-one, status," },
clientProfile: { type: Schema.Types.ObjectId, ref: "profiles", comment: "Client Profile, dropdown, false, true, true, true, true, true, true, profiles, profiles, one-to-one, name," },
applicantName: { type:  String , comment: "Applicant Name, p, false, true, true, true, true, true, true, , , , ," },
referenceNo: { type:  String , comment: "Reference No, p, false, true, true, true, true, true, true, , , , ," },
approvalDate: { type: Date, comment: "Approval Date, p_date, false, true, true, true, true, true, true, , , , ," },
validityDays: { type: Number, comment: "Validity Days, p_number, false, true, true, true, true, true, true, , , , ," },
securityDescription: { type:  String , comment: "Security Description, p, false, true, true, true, true, true, true, , , , ," },
estimatedValue: { type: Number, comment: "Estimated Value, p_number, false, true, true, true, true, true, true, , , , ," },
purchasePrice: { type: Number, comment: "Purchase Price, currency, false, true, true, true, true, true, true, , , , ," },
grossLoanAmount: { type: Number, comment: "Gross Loan Amount, p_number, false, true, true, true, true, true, true, , , , ," },
maxLtvPercentage: { type: Number, comment: "Max Ltv Percentage, p_number, false, true, true, true, true, true, true, , , , ," },
loanTermMonths: { type: Number, comment: "Loan Term Months, p_number, false, true, true, true, true, true, true, , , , ," },
arrangementFeePercentage: { type: Number, comment: "Arrangement Fee Percentage, p_number, false, true, true, true, true, true, true, , , , ," },
concessionaryInterestRateMonthly: { type: Number, comment: "Concessionary Interest Rate Monthly, p_number, false, true, true, true, true, true, true, , , , ," },
standardInterestRateMonthly: { type: Number, comment: "Standard Interest Rate Monthly, p_number, false, true, true, true, true, true, true, , , , ," },
monthlyInterestPaymentsCharges: { type: Number, comment: "Monthly Interest Payments Charges, p_number, false, true, true, true, true, true, true, , , , ," },
advanceInterestAmount: { type: Number, comment: "Advance Interest Amount, p_number, false, true, true, true, true, true, true, , , , ," },
exitStrategyCondition: { type:  String , comment: "Exit Strategy Condition, p, false, true, true, true, true, true, true, , , , ," },
status: { type:  String , comment: "Status, p, false, true, true, true, true, true, true, , , , ," },
generatedPdfDocument: { type:  [Schema.Types.ObjectId], ref: "document_storages" , comment: "Generated Pdf Document, file_upload, false, true, true, true, true, true, true, , , , ," },
generatedByProfile: { type: Schema.Types.ObjectId, ref: "profiles", comment: "Generated By Profile, dropdown, false, true, true, true, true, true, true, profiles, profiles, one-to-one, name," },

            createdBy: { type: Schema.Types.ObjectId, ref: "users", required: true },
            updatedBy: { type: Schema.Types.ObjectId, ref: "users", required: true },
          }, { timestamps: true });
      
       
        if (mongooseClient.modelNames().includes(modelName)) {
          mongooseClient.deleteModel(modelName);
        }
        return mongooseClient.model(modelName, schema);
        
      };